/*
LEEWAY HEADER — DO NOT REMOVE

COLOR_ONION_HEX:
NEON=#39FF14
FLUO=#0DFF94
PASTEL=#C7FFD8

ICON_ASCII:
family=lucide
glyph=key

AGENTS:
ASSESS
ALIGN
AUDIT

REGION: CORE.LEEWAY
TAG: CORE.LEEWAY.CAPABILITY_REGISTRY
DESCRIPTION: Enforceable capabilities defining agent visual, content, and system permissions with Growth Lanes
AUTHORITY: LeeWay-Standards
DISCOVERY_PIPELINE: Standards -> Integrated -> Runtime -> Projections
LICENSE: PROPRIETARY
*/

export interface LeeWayAgentCapability {
  capabilityId: string;
  label: string;
  description: string;
  agentId: string;
  ownerAgentName: string;
  allowedScreens: string[];
  allowedWorkflows: string[];
  allowedActions: string[];
  allowedSchemaPaths: string[];
  allowedPublicRegions: string[];
  allowedAdminRegions: string[];
  allowedTools: string[];
  allowedMcpServers: string[];
  allowedExecutionEnvironments: string[];
  requiresHumanApproval: boolean;
  canApplyDraftChanges: boolean;
  canPublish: boolean;
  riskLevel: "low" | "medium" | "high" | "critical";
  lane: "GREEN" | "YELLOW" | "RED";
  telemetryStreamIds: string[];
  auditCategories: string[];
  blockedActions: string[];
  lawReferences: string[];
}

export const LEEWAY_CAPABILITY_REGISTRY: LeeWayAgentCapability[] = [
  {
    capabilityId: "content.edit.propose",
    label: "Propose Storefront Content Edits",
    description: "Allows the agent to write copy, draft adjustments, and propose hero text or guide updates.",
    agentId: "muse-editorial-agent",
    ownerAgentName: "Muse",
    allowedScreens: ["site-control", "publishing"],
    allowedWorkflows: ["workflow.content.hero.rewrite", "workflow.content.faq.refine"],
    allowedActions: ["propose.hero.rewrite", "propose.faq.refine"],
    allowedSchemaPaths: ["home.hero", "pages.faq"],
    allowedPublicRegions: ["hero", "faq"],
    allowedAdminRegions: ["site-control"],
    allowedTools: ["textGenerators", "schemaValidator"],
    allowedMcpServers: ["filesystem-mcp", "document-retrieval-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "medium",
    lane: "GREEN",
    telemetryStreamIds: ["stream.muse.content"],
    auditCategories: ["content.propose"],
    blockedActions: ["publish.production", "delete.product"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "content.edit.applyDraft",
    label: "Apply Approved Staged Draft Content",
    description: "Applies validated content draft edits to the local database buffer after human sign-off.",
    agentId: "forge-persistence-agent",
    ownerAgentName: "Forge",
    allowedScreens: ["site-control", "publishing"],
    allowedWorkflows: ["workflow.content.commit"],
    allowedActions: ["commit.draft.patch"],
    allowedSchemaPaths: ["home", "pages", "checkout"],
    allowedPublicRegions: ["global"],
    allowedAdminRegions: ["site-control", "publishing"],
    allowedTools: ["databaseWriter"],
    allowedMcpServers: ["product-registry-mcp"],
    allowedExecutionEnvironments: ["sandbox", "local"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "medium",
    lane: "GREEN",
    telemetryStreamIds: ["stream.forge.state"],
    auditCategories: ["content.mutate"],
    blockedActions: ["publish.production"],
    lawReferences: ["LAW-0001", "LAW-0003", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "theme.update.propose",
    label: "Propose Experience Theme Harmonization",
    description: "Suggests brand color palettes, fonts, and radii matching design guidelines.",
    agentId: "aura-media-agent",
    ownerAgentName: "Aura",
    allowedScreens: ["layout", "site-control"],
    allowedWorkflows: ["workflow.theme.palette.propose"],
    allowedActions: ["propose.theme.colors"],
    allowedSchemaPaths: ["theme"],
    allowedPublicRegions: ["theme"],
    allowedAdminRegions: ["layout"],
    allowedTools: ["colorAnalyzer", "fontSelector"],
    allowedMcpServers: ["media-library-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "low",
    lane: "GREEN",
    telemetryStreamIds: ["stream.aura.visual"],
    auditCategories: ["theme.propose"],
    blockedActions: ["publish.production", "overwrite.metadata"],
    lawReferences: ["LAW-0001", "LAW-0004", "LAW-0006", "LAW-0009", "LAW-0016"]
  },
  {
    capabilityId: "theme.update.applyDraft",
    label: "Apply Theme Styles to Staged Draft",
    description: "Applies approved experience preferences to the active global CSS variables.",
    agentId: "avion-assistant-agent",
    ownerAgentName: "Avion",
    allowedScreens: ["layout", "site-control"],
    allowedWorkflows: ["workflow.theme.palette.applyDraft"],
    allowedActions: ["apply.theme.colors"],
    allowedSchemaPaths: ["theme"],
    allowedPublicRegions: ["theme"],
    allowedAdminRegions: ["layout"],
    allowedTools: ["cssVariableUpdater"],
    allowedMcpServers: [],
    allowedExecutionEnvironments: ["sandbox", "local"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "medium",
    lane: "GREEN",
    telemetryStreamIds: ["stream.avion.experience"],
    auditCategories: ["theme.mutate"],
    blockedActions: ["publish.production"],
    lawReferences: ["LAW-0001", "LAW-0004", "LAW-0006", "LAW-0009", "LAW-0016"]
  },
  {
    capabilityId: "layout.reorder.propose",
    label: "Propose Collection Layout Configurations",
    description: "Proposes structural updates to page layout configurations.",
    agentId: "navigator-routing-agent",
    ownerAgentName: "Navigator",
    allowedScreens: ["layout"],
    allowedWorkflows: ["workflow.layout.section.reorder"],
    allowedActions: ["propose.layout.order"],
    allowedSchemaPaths: ["layout"],
    allowedPublicRegions: ["layout"],
    allowedAdminRegions: ["layout"],
    allowedTools: ["layoutSimulator"],
    allowedMcpServers: [],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "low",
    lane: "GREEN",
    telemetryStreamIds: ["stream.navigator.navigation"],
    auditCategories: ["layout.propose"],
    blockedActions: ["publish.production"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "layout.reorder.applyDraft",
    label: "Apply Staged Section Ordering Layouts",
    description: "Mutates the structural layout list elements within the draft JSON block.",
    agentId: "nova-frontend-agent",
    ownerAgentName: "Nova",
    allowedScreens: ["layout"],
    allowedWorkflows: ["workflow.layout.section.visibility"],
    allowedActions: ["apply.layout.order"],
    allowedSchemaPaths: ["layout"],
    allowedPublicRegions: ["layout"],
    allowedAdminRegions: ["layout"],
    allowedTools: ["layoutBuilder"],
    allowedMcpServers: [],
    allowedExecutionEnvironments: ["sandbox", "local"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "medium",
    lane: "GREEN",
    telemetryStreamIds: ["stream.nova.ui"],
    auditCategories: ["layout.mutate"],
    blockedActions: ["publish.production"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "product.edit.propose",
    label: "Propose Catalog Product Refinements",
    description: "Proposes copywriting edits to loose diamond passports, styling notes, or details.",
    agentId: "orion-catalog-agent",
    ownerAgentName: "Orion",
    allowedScreens: ["products"],
    allowedWorkflows: ["workflow.product.description.improve"],
    allowedActions: ["propose.product.edit"],
    allowedSchemaPaths: ["products"],
    allowedPublicRegions: ["shop", "diamonds"],
    allowedAdminRegions: ["products"],
    allowedTools: ["productDescriber"],
    allowedMcpServers: ["product-registry-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "medium",
    lane: "GREEN",
    telemetryStreamIds: ["stream.orion.catalog"],
    auditCategories: ["catalog.propose"],
    blockedActions: ["publish.production", "delete.product"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "product.edit.applyDraft",
    label: "Apply Staged Catalog Product Updates",
    description: "Commits loose diamond passports or product metadata modifications to local draft states.",
    agentId: "forge-persistence-agent",
    ownerAgentName: "Forge",
    allowedScreens: ["products"],
    allowedWorkflows: ["workflow.product.badge.generate"],
    allowedActions: ["apply.product.edit"],
    allowedSchemaPaths: ["products"],
    allowedPublicRegions: ["shop", "diamonds"],
    allowedAdminRegions: ["products"],
    allowedTools: ["catalogStager"],
    allowedMcpServers: ["product-registry-mcp"],
    allowedExecutionEnvironments: ["sandbox", "local"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "medium",
    lane: "GREEN",
    telemetryStreamIds: ["stream.forge.state"],
    auditCategories: ["catalog.mutate"],
    blockedActions: ["publish.production"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "media.assign.propose",
    label: "Propose Media Library Alt-Tags",
    description: "Examines storefront product media and recommends descriptive luxury alt tags.",
    agentId: "aura-media-agent",
    ownerAgentName: "Aura",
    allowedScreens: ["products", "site-control"],
    allowedWorkflows: ["workflow.media.altText.generate"],
    allowedActions: ["propose.media.altText"],
    allowedSchemaPaths: ["home", "products"],
    allowedPublicRegions: ["global"],
    allowedAdminRegions: ["site-control"],
    allowedTools: ["imageAnalyzer"],
    allowedMcpServers: ["media-library-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "low",
    lane: "GREEN",
    telemetryStreamIds: ["stream.aura.visual"],
    auditCategories: ["media.propose"],
    blockedActions: ["publish.production"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "media.assign.applyDraft",
    label: "Apply Staged Media Alt-Tags",
    description: "Applies generated alt tag annotations to the active draft registry.",
    agentId: "nova-frontend-agent",
    ownerAgentName: "Nova",
    allowedScreens: ["products", "site-control"],
    allowedWorkflows: ["workflow.media.commit"],
    allowedActions: ["apply.media.altText"],
    allowedSchemaPaths: ["home", "products"],
    allowedPublicRegions: ["global"],
    allowedAdminRegions: ["site-control"],
    allowedTools: ["mediaWriter"],
    allowedMcpServers: ["media-library-mcp"],
    allowedExecutionEnvironments: ["sandbox", "local"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "low",
    lane: "GREEN",
    telemetryStreamIds: ["stream.nova.ui"],
    auditCategories: ["media.mutate"],
    blockedActions: ["publish.production"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"]
  },
  {
    capabilityId: "standards.validate",
    label: "Audit System Compliance Standard",
    description: "Inspects source files, DOM identifiers, settings scoping, and emits real-time validation warnings.",
    agentId: "sentinel-compliance-agent",
    ownerAgentName: "Sentinel",
    allowedScreens: ["leeway-standards"],
    allowedWorkflows: ["workflow.standards.source.inspect"],
    allowedActions: ["run.compliance.audit"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards"],
    allowedTools: ["complianceAnalyzer"],
    allowedMcpServers: ["filesystem-mcp", "telemetry-mcp"],
    allowedExecutionEnvironments: ["sandbox", "local"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "YELLOW",
    telemetryStreamIds: ["stream.sentinel.compliance"],
    auditCategories: ["standards.audit"],
    blockedActions: ["mutate.content", "publish.production"],
    lawReferences: ["LAW-0002", "LAW-0005", "LAW-0007", "LAW-0014"]
  },
  {
    capabilityId: "code.patch.propose",
    label: "Propose System Code Patches",
    description: "Analyzes React structural layouts or admin portal features and drafts isolated code updates.",
    agentId: "nova-frontend-agent",
    ownerAgentName: "Nova",
    allowedScreens: ["leeway-standards"],
    allowedWorkflows: ["workflow.code.frontend.patch.propose"],
    allowedActions: ["draft.frontend.patch"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards"],
    allowedTools: ["codeCompiler"],
    allowedMcpServers: ["code-patch-mcp", "vs-code-bridge-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: true,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "high",
    lane: "YELLOW",
    telemetryStreamIds: ["stream.nova.ui"],
    auditCategories: ["code.propose"],
    blockedActions: ["write.file.direct"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009", "LAW-0011", "LAW-0013"]
  },
  {
    capabilityId: "code.patch.applyApproved",
    label: "Apply Human-Approved Code Patches",
    description: "Applies audited, signed code patches to the workspace via VS Code MCP bridge integrations.",
    agentId: "forge-persistence-agent",
    ownerAgentName: "Forge",
    allowedScreens: ["leeway-standards"],
    allowedWorkflows: ["workflow.code.backend.patch.propose"],
    allowedActions: ["commit.code.patch"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards"],
    allowedTools: ["fileWriter"],
    allowedMcpServers: ["code-patch-mcp", "vs-code-bridge-mcp"],
    allowedExecutionEnvironments: ["local", "production"],
    requiresHumanApproval: true,
    canApplyDraftChanges: true,
    canPublish: false,
    riskLevel: "critical",
    lane: "RED",
    telemetryStreamIds: ["stream.forge.state"],
    auditCategories: ["code.mutate"],
    blockedActions: ["delete.system.core"],
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009", "LAW-0011", "LAW-0013"]
  },
  {
    capabilityId: "settings.explain",
    label: "Explain System Capability Boundaries",
    description: "Assists the human owner in navigating, explaining, and understanding all available AdminOS settings.",
    agentId: "avion-assistant-agent",
    ownerAgentName: "Avion",
    allowedScreens: ["dashboard", "orders", "products", "members", "agents", "site-control", "layout", "leeway-standards", "publishing"],
    allowedWorkflows: ["workflow.owner.help.explainCapability"],
    allowedActions: ["query.capability.details"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["*"],
    allowedTools: ["helpLookup"],
    allowedMcpServers: ["document-retrieval-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "GREEN",
    telemetryStreamIds: ["stream.avion.experience"],
    auditCategories: ["help.query"],
    blockedActions: ["mutate.anything"],
    lawReferences: ["LAW-0018"]
  },
  {
    capabilityId: "owner.guide",
    label: "Sovereign Concierge Guidance",
    description: "Translates human language prompts and goals into structured AdminOS proposals and layouts.",
    agentId: "avion-assistant-agent",
    ownerAgentName: "Avion",
    allowedScreens: ["*"],
    allowedWorkflows: ["workflow.owner.help.explainCapability"],
    allowedActions: ["assist.owner.workspace"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["*"],
    allowedTools: ["intentParser"],
    allowedMcpServers: [],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "GREEN",
    telemetryStreamIds: ["stream.avion.experience"],
    auditCategories: ["help.query"],
    blockedActions: ["mutate.anything"],
    lawReferences: ["LAW-0001", "LAW-0018"]
  },
  {
    capabilityId: "telemetry.inspect",
    label: "Inspect Real-time Telemetry Streams",
    description: "Fetches and displays active agent action events and system metrics.",
    agentId: "sentinel-compliance-agent",
    ownerAgentName: "Sentinel",
    allowedScreens: ["leeway-standards", "agents"],
    allowedWorkflows: ["workflow.telemetry.stream.inspect"],
    allowedActions: ["query.telemetry.data"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards", "agents"],
    allowedTools: ["telemetryQuerier"],
    allowedMcpServers: ["telemetry-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "YELLOW",
    telemetryStreamIds: ["stream.sentinel.compliance"],
    auditCategories: ["telemetry.read"],
    blockedActions: [],
    lawReferences: ["LAW-0007"]
  },
  {
    capabilityId: "audit.inspect",
    label: "Inspect Compliance Audit Timeline",
    description: "Renders historical action records, modification logs, and compliance score metrics.",
    agentId: "ledger-audit-agent",
    ownerAgentName: "Ledger",
    allowedScreens: ["leeway-standards"],
    allowedWorkflows: ["workflow.audit.timeline.inspect"],
    allowedActions: ["read.audit.logs"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards"],
    allowedTools: ["auditTimelineParser"],
    allowedMcpServers: ["audit-log-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "YELLOW",
    telemetryStreamIds: ["stream.ledger.audit"],
    auditCategories: ["audit.read"],
    blockedActions: [],
    lawReferences: ["LAW-0002", "LAW-0007", "LAW-0014"]
  },
  {
    capabilityId: "mcp.status.inspect",
    label: "Inspect Governed MCP Connection States",
    description: "Exposes active model context protocol links, heartbeats, and permissions settings.",
    agentId: "sentinel-compliance-agent",
    ownerAgentName: "Sentinel",
    allowedScreens: ["leeway-standards"],
    allowedWorkflows: ["workflow.mcp.status.inspect"],
    allowedActions: ["query.mcp.heartbeats"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards"],
    allowedTools: ["mcpChecker"],
    allowedMcpServers: [],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "YELLOW",
    telemetryStreamIds: ["stream.sentinel.compliance"],
    auditCategories: ["mcp.read"],
    blockedActions: [],
    lawReferences: ["LAW-0011"]
  },
  {
    capabilityId: "vscode.bridge.inspect",
    label: "Inspect Governed VS Code SDK Bridge State",
    description: "Validates active LeeWay VS Code bridge link heartbeats.",
    agentId: "atlas-knowledge-agent",
    ownerAgentName: "Atlas",
    allowedScreens: ["leeway-standards"],
    allowedWorkflows: ["workflow.vscode.bridge.inspect"],
    allowedActions: ["query.vscode.handshake"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards"],
    allowedTools: ["bridgeChecker"],
    allowedMcpServers: ["vs-code-bridge-mcp"],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "YELLOW",
    telemetryStreamIds: ["stream.atlas.memory"],
    auditCategories: ["bridge.read"],
    blockedActions: [],
    lawReferences: ["LAW-0013"]
  },
  {
    capabilityId: "runtime.authority.inspect",
    label: "Inspect Governed Runtime Authority State",
    description: "Verifies current sandbox, bootstrap, and live operational permissions blocks.",
    agentId: "shield-safety-agent",
    ownerAgentName: "Shield",
    allowedScreens: ["leeway-standards"],
    allowedWorkflows: ["workflow.standards.source.inspect"],
    allowedActions: ["query.runtime.authority"],
    allowedSchemaPaths: [],
    allowedPublicRegions: [],
    allowedAdminRegions: ["leeway-standards"],
    allowedTools: ["authorityChecker"],
    allowedMcpServers: [],
    allowedExecutionEnvironments: ["sandbox"],
    requiresHumanApproval: false,
    canApplyDraftChanges: false,
    canPublish: false,
    riskLevel: "low",
    lane: "YELLOW",
    telemetryStreamIds: ["stream.shield.safety"],
    auditCategories: ["authority.read"],
    blockedActions: [],
    lawReferences: ["LAW-0005"]
  }
];
