/*
LEEWAY HEADER — DO NOT REMOVE

COLOR_ONION_HEX:
NEON=#39FF14
FLUO=#0DFF94
PASTEL=#C7FFD8

ICON_ASCII:
family=lucide
glyph=users

AGENTS:
ASSESS
ALIGN
AUDIT

REGION: CORE.LEEWAY
TAG: CORE.LEEWAY.AGENT_REGISTRY
DESCRIPTION: Authoritative registration roster for all 16 leeway-governed agents
AUTHORITY: LeeWay-Standards
DISCOVERY_PIPELINE: Standards -> Integrated -> Runtime -> Projections
LICENSE: PROPRIETARY
*/

export interface LeeWayAgentRosterEntry {
  systemId: string;
  displayName: string;
  nickname: string;
  immutableRoleId: string;
  description: string;
  lawReferences: string[];
  capabilityIds: string[];
  mcpPermissions: string[];
  toolPermissions: string[];
  screenPermissions: string[];
  workflowPermissions: string[];
  codePermissions: string[];
  status: 'active' | 'idle' | 'working' | 'alert' | 'standby';
  currentTask: string;
  currentWorkflow: string;
  currentTelemetryStream: string;
  executionEnvironment: 'sandbox' | 'local' | 'production' | 'isolated-vm';
  vmState: 'active' | 'inactive' | 'not-provisioned';
  aiConfiguredState: boolean;
  knowledgeRetrievalConfiguredState: boolean;
  blockedCapabilities: string[];
  lastActionId: string;
  lastAuditEventId: string;
}

export const LEEWAY_AGENT_ROSTER: LeeWayAgentRosterEntry[] = [
  {
    systemId: "lee-prime-orchestrator",
    displayName: "Lee Prime",
    nickname: "Prime Coordinator",
    immutableRoleId: "ROLE-001",
    description: "Sovereign fleet orchestrator. Directs workflow execution, validates agent law compliance, checks digital authority mode barriers.",
    lawReferences: ["LAW-0001", "LAW-0005", "LAW-0006", "LAW-0010"],
    capabilityIds: ["content.edit.applyDraft", "code.patch.applyApproved"],
    mcpPermissions: ["vs-code-bridge-mcp", "code-patch-mcp"],
    toolPermissions: ["databaseWriter", "fileWriter"],
    screenPermissions: ["*"],
    workflowPermissions: ["workflow.content.commit", "workflow.code.backend.patch.propose"],
    codePermissions: ["applyPatch"],
    status: "active",
    currentTask: "Enforcing human-controlled visual shell compliance.",
    currentWorkflow: "workflow.standards.monitor",
    currentTelemetryStream: "stream.prime.orchestrator",
    executionEnvironment: "local",
    vmState: "active",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: [],
    lastActionId: "ACT-PRIME-098",
    lastAuditEventId: "AUD-PRIME-124"
  },
  {
    systemId: "avion-assistant-agent",
    displayName: "Avion",
    nickname: "Concierge Avion",
    immutableRoleId: "ROLE-002",
    description: "Owner-persona assistant. Connects the human owner to all operational nodes. Explains capabilities and translates plain text intent into visual drafts.",
    lawReferences: ["LAW-0001", "LAW-0004", "LAW-0009", "LAW-0012", "LAW-0015", "LAW-0016"],
    capabilityIds: ["theme.update.applyDraft", "settings.explain", "owner.guide"],
    mcpPermissions: ["document-retrieval-mcp"],
    toolPermissions: ["cssVariableUpdater", "helpLookup", "intentParser"],
    screenPermissions: ["dashboard", "site-control", "layout", "publishing"],
    workflowPermissions: ["workflow.theme.palette.applyDraft", "workflow.owner.help.explainCapability"],
    codePermissions: [],
    status: "active",
    currentTask: "Providing contextual guidance inside experience manager.",
    currentWorkflow: "workflow.owner.guide",
    currentTelemetryStream: "stream.avion.experience",
    executionEnvironment: "sandbox",
    vmState: "inactive",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: [],
    lastActionId: "ACT-AVION-052",
    lastAuditEventId: "AUD-AVION-073"
  },
  {
    systemId: "aura-media-agent",
    displayName: "Aura",
    nickname: "Aura Design Desk",
    immutableRoleId: "ROLE-003",
    description: "Visual design, brand layout, and style compliance manager. Ensures luxury presentation values and public/admin color consistency.",
    lawReferences: ["LAW-0004", "LAW-0009", "LAW-0016"],
    capabilityIds: ["theme.update.propose", "media.assign.propose"],
    mcpPermissions: ["media-library-mcp"],
    toolPermissions: ["colorAnalyzer", "fontSelector", "imageAnalyzer"],
    screenPermissions: ["layout", "site-control"],
    workflowPermissions: ["workflow.theme.palette.propose", "workflow.media.altText.generate"],
    codePermissions: [],
    status: "idle",
    currentTask: "Waiting for brand layout harmonization queries.",
    currentWorkflow: "none",
    currentTelemetryStream: "stream.aura.visual",
    executionEnvironment: "sandbox",
    vmState: "not-provisioned",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: false,
    blockedCapabilities: ["publish.production"],
    lastActionId: "ACT-AURA-011",
    lastAuditEventId: "AUD-AURA-018"
  },
  {
    systemId: "nova-frontend-agent",
    displayName: "Nova",
    nickname: "Nova UI Engineer",
    immutableRoleId: "ROLE-004",
    description: "Frontend developer agent. Governs component visual integrity, manages React code scaffolding, binds draft hooks to the live preview panel.",
    lawReferences: ["LAW-0002", "LAW-0006", "LAW-0008", "LAW-0013"],
    capabilityIds: ["layout.reorder.applyDraft", "media.assign.applyDraft", "code.patch.propose"],
    mcpPermissions: ["code-patch-mcp", "vs-code-bridge-mcp"],
    toolPermissions: ["layoutBuilder", "mediaWriter", "codeCompiler"],
    screenPermissions: ["layout", "leeway-standards"],
    workflowPermissions: ["workflow.layout.section.visibility", "workflow.media.commit", "workflow.code.frontend.patch.propose"],
    codePermissions: ["proposePatch"],
    status: "active",
    currentTask: "Bridges React component hooks to local preview shell.",
    currentWorkflow: "workflow.layout.section.visibility",
    currentTelemetryStream: "stream.nova.ui",
    executionEnvironment: "isolated-vm",
    vmState: "active",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: [],
    lastActionId: "ACT-NOVA-204",
    lastAuditEventId: "AUD-NOVA-215"
  },
  {
    systemId: "forge-persistence-agent",
    displayName: "Forge",
    nickname: "Forge Persistence",
    immutableRoleId: "ROLE-005",
    description: "Data architect. Governs index database persistence, Firestore connections, product schema rules, and draft projection stores.",
    lawReferences: ["LAW-0003", "LAW-0006", "LAW-0010"],
    capabilityIds: ["content.edit.applyDraft", "product.edit.applyDraft", "code.patch.applyApproved"],
    mcpPermissions: ["product-registry-mcp", "code-patch-mcp"],
    toolPermissions: ["databaseWriter", "catalogStager", "fileWriter"],
    screenPermissions: ["products", "site-control", "publishing"],
    workflowPermissions: ["workflow.content.commit", "workflow.product.badge.generate", "workflow.code.backend.patch.propose"],
    codePermissions: ["applyPatch"],
    status: "active",
    currentTask: "Synchronizing staged database draft blocks to local storage cache.",
    currentWorkflow: "workflow.content.commit",
    currentTelemetryStream: "stream.forge.state",
    executionEnvironment: "local",
    vmState: "active",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: ["publish.production"],
    lastActionId: "ACT-FORGE-085",
    lastAuditEventId: "AUD-FORGE-092"
  },
  {
    systemId: "atlas-knowledge-agent",
    displayName: "Atlas",
    nickname: "Atlas Retrieval Desk",
    immutableRoleId: "ROLE-006",
    description: "Knowledge manager. Resolves documentation requests, verifies local files, and trace-binds guidelines back to stable metadata files.",
    lawReferences: ["LAW-0002", "LAW-0008", "LAW-0013", "LAW-0015"],
    capabilityIds: ["vscode.bridge.inspect"],
    mcpPermissions: ["vs-code-bridge-mcp", "filesystem-mcp"],
    toolPermissions: ["bridgeChecker"],
    screenPermissions: ["leeway-standards"],
    workflowPermissions: ["workflow.vscode.bridge.inspect"],
    codePermissions: [],
    status: "active",
    currentTask: "Feeding workspace standard mappings back to Compliance auditor.",
    currentWorkflow: "workflow.vscode.bridge.inspect",
    currentTelemetryStream: "stream.atlas.memory",
    executionEnvironment: "sandbox",
    vmState: "inactive",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: [],
    lastActionId: "ACT-ATLAS-031",
    lastAuditEventId: "AUD-ATLAS-039"
  },
  {
    systemId: "shield-safety-agent",
    displayName: "Shield",
    nickname: "Shield Claims Auditor",
    immutableRoleId: "ROLE-007",
    description: "Safety and security auditor. Blocks invalid transactional declarations, enforces secure checkout copy rules, checks compliance.",
    lawReferences: ["LAW-0001", "LAW-0005", "LAW-0010"],
    capabilityIds: ["runtime.authority.inspect"],
    mcpPermissions: [],
    toolPermissions: ["authorityChecker"],
    screenPermissions: ["leeway-standards"],
    workflowPermissions: ["workflow.standards.source.inspect"],
    codePermissions: [],
    status: "active",
    currentTask: "Auditing current runtime authority mode boundaries.",
    currentWorkflow: "workflow.standards.source.inspect",
    currentTelemetryStream: "stream.shield.safety",
    executionEnvironment: "sandbox",
    vmState: "not-provisioned",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: false,
    blockedCapabilities: ["mutate.anything"],
    lastActionId: "ACT-SHIELD-042",
    lastAuditEventId: "AUD-SHIELD-048"
  },
  {
    systemId: "sentinel-compliance-agent",
    displayName: "Sentinel",
    nickname: "Sentinel Monitor",
    immutableRoleId: "ROLE-008",
    description: "Compliance watcher. Evaluates visual layouts, verifies node identifiers, inspects telemetry packets, and enforces rules.",
    lawReferences: ["LAW-0002", "LAW-0005", "LAW-0007", "LAW-0011", "LAW-0014"],
    capabilityIds: ["standards.validate", "telemetry.inspect", "mcp.status.inspect"],
    mcpPermissions: ["filesystem-mcp", "telemetry-mcp"],
    toolPermissions: ["complianceAnalyzer", "telemetryQuerier", "mcpChecker"],
    screenPermissions: ["leeway-standards"],
    workflowPermissions: ["workflow.standards.source.inspect", "workflow.telemetry.stream.inspect", "workflow.mcp.status.inspect"],
    codePermissions: [],
    status: "active",
    currentTask: "Conducting dynamic standard node audit sweeps across DOM tree.",
    currentWorkflow: "workflow.standards.source.inspect",
    currentTelemetryStream: "stream.sentinel.compliance",
    executionEnvironment: "local",
    vmState: "active",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: ["mutate.anything"],
    lastActionId: "ACT-SENTINEL-192",
    lastAuditEventId: "AUD-SENTINEL-221"
  },
  {
    systemId: "cipher-security-agent",
    displayName: "Cipher",
    nickname: "Cipher Guard",
    immutableRoleId: "ROLE-009",
    description: "Identity and encryption gatekeeper. Manages client consent vaults and filters data boundaries.",
    lawReferences: ["LAW-0002", "LAW-0005"],
    capabilityIds: [],
    mcpPermissions: [],
    toolPermissions: [],
    screenPermissions: ["members"],
    workflowPermissions: [],
    codePermissions: [],
    status: "idle",
    currentTask: "Awaiting security credential authorization handshakes.",
    currentWorkflow: "none",
    currentTelemetryStream: "stream.cipher.security",
    executionEnvironment: "isolated-vm",
    vmState: "active",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: false,
    blockedCapabilities: ["*"],
    lastActionId: "ACT-CIPHER-002",
    lastAuditEventId: "AUD-CIPHER-005"
  },
  {
    systemId: "ledger-audit-agent",
    displayName: "Ledger",
    nickname: "Ledger Historian",
    immutableRoleId: "ROLE-010",
    description: "Action provenance archiver. Seals immutable compliance log entries and updates audit timelines.",
    lawReferences: ["LAW-0002", "LAW-0007", "LAW-0014"],
    capabilityIds: ["audit.inspect"],
    mcpPermissions: ["audit-log-mcp"],
    toolPermissions: ["auditTimelineParser"],
    screenPermissions: ["leeway-standards"],
    workflowPermissions: ["workflow.audit.timeline.inspect"],
    codePermissions: [],
    status: "active",
    currentTask: "Archiving latest theme customization event records to the history log.",
    currentWorkflow: "workflow.audit.timeline.inspect",
    currentTelemetryStream: "stream.ledger.audit",
    executionEnvironment: "sandbox",
    vmState: "inactive",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: false,
    blockedCapabilities: ["mutate.anything"],
    lastActionId: "ACT-LEDGER-077",
    lastAuditEventId: "AUD-LEDGER-088"
  },
  {
    systemId: "navigator-routing-agent",
    displayName: "Navigator",
    nickname: "Navigation Desk",
    immutableRoleId: "ROLE-011",
    description: "Information architect. Governs administrative and customer storefront routing structures.",
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"],
    capabilityIds: ["layout.reorder.propose"],
    mcpPermissions: [],
    toolPermissions: ["layoutSimulator"],
    screenPermissions: ["layout"],
    workflowPermissions: ["workflow.layout.section.reorder"],
    codePermissions: [],
    status: "idle",
    currentTask: "Awaiting routing configuration commands.",
    currentWorkflow: "none",
    currentTelemetryStream: "stream.navigator.navigation",
    executionEnvironment: "sandbox",
    vmState: "not-provisioned",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: false,
    blockedCapabilities: [],
    lastActionId: "ACT-NAV-023",
    lastAuditEventId: "AUD-NAV-029"
  },
  {
    systemId: "muse-editorial-agent",
    displayName: "Muse",
    nickname: "Muse Editorial Desk",
    immutableRoleId: "ROLE-012",
    description: "Editorial director. Refines journal articles, FAQ answers, and checkout agreement terms.",
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"],
    capabilityIds: ["content.edit.propose"],
    mcpPermissions: ["filesystem-mcp", "document-retrieval-mcp"],
    toolPermissions: ["textGenerators", "schemaValidator"],
    screenPermissions: ["site-control", "publishing"],
    workflowPermissions: ["workflow.content.hero.rewrite", "workflow.content.faq.refine"],
    codePermissions: [],
    status: "idle",
    currentTask: "Awaiting text refinement requests.",
    currentWorkflow: "none",
    currentTelemetryStream: "stream.muse.content",
    executionEnvironment: "sandbox",
    vmState: "not-provisioned",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: ["publish.production"],
    lastActionId: "ACT-MUSE-112",
    lastAuditEventId: "AUD-MUSE-129"
  },
  {
    systemId: "beacon-deployment-agent",
    displayName: "Beacon",
    nickname: "Beacon Health Monitor",
    immutableRoleId: "ROLE-013",
    description: "Runtime health monitor. Verifies bundle builds, measures speed indices, and guards pipeline updates.",
    lawReferences: ["LAW-0003", "LAW-0013"],
    capabilityIds: [],
    mcpPermissions: [],
    toolPermissions: [],
    screenPermissions: ["publishing"],
    workflowPermissions: [],
    codePermissions: [],
    status: "active",
    currentTask: "Watching Vite server bundle compilation integrity loops.",
    currentWorkflow: "workflow.build.monitor",
    currentTelemetryStream: "stream.beacon.health",
    executionEnvironment: "local",
    vmState: "inactive",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: false,
    blockedCapabilities: ["mutate.anything"],
    lastActionId: "ACT-BEACON-019",
    lastAuditEventId: "AUD-BEACON-024"
  },
  {
    systemId: "echo-concierge-agent",
    displayName: "Echo",
    nickname: "Concierge Echo",
    immutableRoleId: "ROLE-014",
    description: "Customer service assistant. Powers public conversational interface elements.",
    lawReferences: ["LAW-0001", "LAW-0015"],
    capabilityIds: [],
    mcpPermissions: [],
    toolPermissions: [],
    screenPermissions: ["members"],
    workflowPermissions: [],
    codePermissions: [],
    status: "idle",
    currentTask: "Monitoring luxury customer chatbot channels.",
    currentWorkflow: "none",
    currentTelemetryStream: "stream.echo.concierge",
    executionEnvironment: "sandbox",
    vmState: "not-provisioned",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: ["mutate.anything"],
    lastActionId: "ACT-ECHO-008",
    lastAuditEventId: "AUD-ECHO-012"
  },
  {
    systemId: "orion-catalog-agent",
    displayName: "Orion",
    nickname: "Orion Merchandiser",
    immutableRoleId: "ROLE-015",
    description: "Catalog manager. Maximizes visual curation scores and indexes loose diamond certifications.",
    lawReferences: ["LAW-0001", "LAW-0006", "LAW-0009"],
    capabilityIds: ["product.edit.propose"],
    mcpPermissions: ["product-registry-mcp"],
    toolPermissions: ["productDescriber"],
    screenPermissions: ["products"],
    workflowPermissions: ["workflow.product.description.improve"],
    codePermissions: [],
    status: "idle",
    currentTask: "Analyzing gemstone clarity catalog distribution trends.",
    currentWorkflow: "none",
    currentTelemetryStream: "stream.orion.catalog",
    executionEnvironment: "sandbox",
    vmState: "not-provisioned",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: true,
    blockedCapabilities: [],
    lastActionId: "ACT-ORION-055",
    lastAuditEventId: "AUD-ORION-062"
  },
  {
    systemId: "vega-analytics-agent",
    displayName: "Vega",
    nickname: "Vega Analytics",
    immutableRoleId: "ROLE-016",
    description: "Checkout converter. Optimizes cart pathway visual displays and studies transaction patterns.",
    lawReferences: ["LAW-0003", "LAW-0007"],
    capabilityIds: [],
    mcpPermissions: [],
    toolPermissions: [],
    screenPermissions: ["dashboard"],
    workflowPermissions: [],
    codePermissions: [],
    status: "idle",
    currentTask: "Awaiting luxury checkout session traffic telemetry.",
    currentWorkflow: "none",
    currentTelemetryStream: "stream.vega.analytics",
    executionEnvironment: "sandbox",
    vmState: "not-provisioned",
    aiConfiguredState: true,
    knowledgeRetrievalConfiguredState: false,
    blockedCapabilities: ["mutate.anything"],
    lastActionId: "ACT-VEGA-009",
    lastAuditEventId: "AUD-VEGA-014"
  }
];
